DROP DATABASE Bookworm_db;

CREATE DATABASE IF NOT EXISTS Bookworm_db;



USE Bookworm_db;

INSERT INTO users (bio, birthday, city, email, favorite_book, favorite_genre, first_name, last_name, password, state, username) VALUES
('I love to read!', '1996-01-29', 'San Antonio', 'users@email.com', 'Coraline', 'Thriller', 'userOne', 'userOneLastName', 'password', 'Texas', 'userOneUsername'),
('Reading is Fun!', '1900-09-23', 'Paris', 'jessica@email.com','Pride and Prejudice', 'Romanece', 'Jessica', 'Mimosa', 'theRed', 'Texas', 'jessicaUser'),
('I guess I like reading', '2011-05-30', 'Manhattan', 'dopeBoy@email.com', 'Skaterz R Us', 'Adventure', 'Jake', 'Macintosh', 'readingisLyfe', 'New York', 'SkaterBoi'),
('Building Generational Wealth', '1977-01-04', 'Altus', 'sara@email.com', 'Rich Dad, Poor Dad', 'Finance', 'Sara', 'Rico', 'password', 'Oklahoma', 'saraUser'),
('Live, laugh, love', '1991-06-04', 'Quana', 'raqel@email.com', 'Babies R Us', 'Parenting', 'Raqel', 'Vasquez', 'loveFamily', 'Texas', 'stellasMom'),
('Love 2 Read', '1948-05-06', 'Los Angeles', 'juan@email.com', 'IT', 'horror', 'Juan', 'Vasquez', 'readingpassword', 'California', 'juanUser'),
('I love Books', '1956-11-08', 'Arlington', 'ama@email.com', 'The Queen', 'Biographies', 'Maria', 'Vasquez', 'ama210', 'Virginia', 'ama210'),
('Books give me joy', '1988-03-15', 'Boise', 'angel@email.com', 'Harry Potter', 'fantasy', 'Angel', 'Vasquez', 'angelzz', 'Idaho','angelUser'),
('Pet Parent', '1922-04-28', 'Clinton','mary@email.com', 'Goosebumps', 'Thriller', 'Craig', 'Baskin', 'craigsKool', 'Maryland', 'craigUser'),
('I love BookWorm Website!!', '1890-01-01', 'Boston', 'book@email.com', 'Diary of Anne Frank', 'Romance', 'Lilibet', 'Windsor', 'password123', 'Massachusets', 'NotTheQueen'),
('Do I need to read! YES I DO', '2003-01-12', 'Anaheim ', 'user@email.com', 'Coraline', 'Thriller', 'Stan', 'Gilbertson', 'password', 'California', 'angelcitydude'),
('Because you kill me You know you do, you fuck', '1992-06-29', 'Dallas', 'knownReader@email.com', 'The Road', 'Sci-Fi', 'Bobby', 'Smith', 'password', 'Texas', 'knownReader' ),
('who needs a bio?!?!', '1989-12-20' , 'dallas', 'dallasboy@email.com', 'lonestar', 'comedy', 'luke', 'lacey', 'password', 'texas', 'dallasboy'),
('live life like no one is watching', '2001-02-05','los angeles', 'losAngel@email.com', 'The Road', 'comedy', 'Chris', 'Blake', 'password', 'california', 'losAngel'),
('One day I will make it big just watch', '1990-03-23', 'arlington', 'shooterstar@email.com', 'hocus pocus', 'horror', 'samantha', 'butters', 'password', 'texas', 'samsam'),
('well I tell you my friend there will be one day', '2004-09-22', 'boston', 'lonewolf@email.com', 'harry potter', 'fiction', 'christy', 'daily', 'password','Massachusetts', 'dailyLiving'),
('funny quotes make great introductions', '1995-04-14', 'san antonio', 'whoamI@email.com', 'the dark path taken', 'mystery', 'bobby', 'gilmore', 'password', 'texas', 'happygilmore'),
('make great introductions', '1995-05-11','san antonio', 'wowthisiscool@email.com', 'the path', 'Romance', 'lucy', 'smith', 'password', 'texas', 'lucylu'),
('life is what you make it homie','1991-07-30', 'roswell', 'wildhog@email.com', 'The Road', 'Biography', 'kyle', 'lara', 'password', 'New Mexico', 'wildhog'),
('simple reading makes life easy', '1998-04-18','new york', 'newworld@email.com', 'cat in the hat', 'adventure', 'Lucas', 'Patterson', 'password','new york', 'newworld');

INSERT INTO book_list(author, book_cover, buy_link, description, genre, isbn, page_count, published_date, purchase_price, rating, book_title) VALUES
                                                                                                                                                  ('Cormac McCarthy','https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1600241424i/6288.jpg', 'https://www.goodreads.com/book/show/6288.The_Road#?ref=nav_brws', 'A searing, postapocalyptic novel destined to become Cormac McCarthy’s masterpiece.
A father and his son walk alone through burned America. Nothing moves in the ravaged landscape save the ash on the wind. It is cold enough to crack stones, and when the snow falls it is gray. The sky is dark. Their destination is the coast, although they don’t know what, if anything, awaits them there. They have nothing; just a pistol to defend themselves against the lawless bands that stalk the road, the clothes they are wearing, a cart of scavenged food—and each other.
The Road is the profoundly moving story of a journey. It boldly imagines a future in which no hope remains, but in which the father and his son, “each the other’s world entire,” are sustained by love. Awesome in the totality of its vision, it is an unflinching meditation on the worst and the best that we are capable of: ultimate destructiveness, desperate tenacity, and the tenderness that keeps two people alive in the face of total devastation.', 'fiction', '9780307265432', '241', 'Oct 21, 2006', '12.99', '4', 'The Road'),
('Aaron Reynolds',
   'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1658939704i/57636300.jpg',
   'https://www.goodreads.com/book/show/57636300-creepy-crayon',
   'Jasper Rabbit has a problem: he is NOT doing well in school. His spelling tests? Disasters. His math quizzes? Frightening to behold. But one day, he finds a crayon lying in the gutter. Purple. Pointy. Perfect. Somehow…it looked happy to see him. And it wants to help.
   At first, Jasper is excited. Everything is going great. His spelling is fantastic. His math is stupendous. And best of all, he doesn’t have to do ANY work! But then the crayon starts acting weird. It’s everywhere, and it wants to do everything. And Jasper must find a way to get rid of it before it takes over his life. The only problem? The creepy crayon will not leave.',
   'Children',
   '9781534465886',
   '48',
   'August 23, 2022',
   '12.99',
   '4.33',
   'Creepy Crayon!'),
('Minh Le','https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1635250930i/59447016.jpg','https://www.goodreads.com/book/show/59447016-the-blur','From the very beginning, there was something different about this child... An ultrasonic voice. Fantastically elastic limbs. Super-magnetic powers. But it wasnt until the child took her first steps that she became: THE BLUR! Nothing can stand in her way as she takes the world by storm: always on the move and darting into danger! All too soon, she is zipping through the days, and zooming over the years... Framed as an origin story, here is a fun superhero romp for kids, filled with bold and bright illustrations, that will pull at the hearstrings of every parent..',
   'Children','9780593377468','40','May 3, 2022','12.99','4','The Blur'),
('Benjamin Cunningham',
   'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1639126498i/59786862.jpg',
   'https://www.goodreads.com/book/show/59786862-the-liar?from_search=true&from_srp=true&qid=xiYP0LZz7V&rank=1',
   'In the mid-1970s, the CIA and KGB were both watching Karel Koecher closely—and they were both convinced he was working for the enemy. They were both right. Traveling with his wife, Hana, Koecher posed as a Czechoslovak asylum seeker and arrived in the US as a Communist sleeper agent. After parlaying a doctorate from Columbia into a job at the CIA, Koecher proceeded to operate as a double agent at the height of the Cold War. Shunning a low profile, the Koechers embraced Manhattan’s high life — with cocaine, swinging and parties emblematic of the times and their penchant for risk. Hana, who was no more than a shy teenager when she arrived, grew into a sophisticated international diamond dealer that relayed messages to Karel’s handlers. Riding a wave of euphoria, the Koechers felt unstoppable. But it was too good to last. Using newly declassified documents, interrogation tapes and extraordinary first-hand accounts from the Koechers themselves, Cunningham reconstructs their double lives and the fading Cold War, where a strange moral fog made it hard to know what truth was being fought for, and to what end.',
   'History',
   '9781541700796',
   '320',
   'August 23, 2022',
   '12.99',
   '3.62',
   'The Liar: How a Double Agent in the CIA Became the Cold Wars Last Honest Man'),
('Amanda Skenandore',
   'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1607322561i/55841940.jpg',
   'https://www.goodreads.com/book/show/55841940-the-second-life-of-mirielle-west?from_search=true&from_srp=true&qid=jYLOcfJFzq&rank=1',
   'Based on the true story of America’s only leper colony, The Second Life of Mirielle West brings vividly to life the Louisiana institution known as Carville, where thousands of people were stripped of their civil rights, branded as lepers, and forcibly quarantined throughout the entire 20th century.
   For Mirielle West, a 1920’s socialite married to a silent film star, the isolation, and powerlessness of the Louisiana Leper Home is an unimaginable fall from her intoxicatingly chic life of bootlegged champagne and the star-studded parties of Hollywood’s Golden Age. When a doctor notices a pale patch of skin on her hand, she’s immediately branded a leper and carted hundreds of miles from home to Carville, taking a new name to spare her family and famous husband the shame that accompanies the disease.
   At first, she hopes her exile will be brief, but those sent to Carville are more prisoners than patients and their disease has no cure. Instead, she must find community and purpose within its walls, struggling to redefine her self-worth while fighting an unchosen fate.
   As a registered nurse, Amanda Skenandore’s medical background adds layers of detail and authenticity to the experiences of patients and medical professionals at Carville – the isolation, stigma, experimental treatments, and disparate community. A tale of repulsion, resilience, and the Roaring ‘20s, The Second Life of Mirielle West is also the story of a health crisis in America’s past, made all the more poignant by the author’s experiences during another, all-too-recent crisis.',
   'History',
   '9781496726513',
   '384',
   'July 27, 2021',
   '12.99',
   '4.27',
   'The Second Life of Mirielle West'),
('Daniel Kahneman',
   'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1317793965i/11468377.jpg',
   'https://www.goodreads.com/book/show/11468377-thinking-fast-and-slow?ref=nav_sb_ss_1_23',
   'In the highly anticipated Thinking, Fast and Slow, Kahneman takes us on a groundbreaking tour of the mind and explains the two systems that drive the way we think. System 1 is fast, intuitive, and emotional; System 2 is slower, more deliberative, and more logical. Kahneman exposes the extraordinary capabilities—and also the faults and biases—of fast thinking, and reveals the pervasive influence of intuitive impressions on our thoughts and behavior. The impact of loss aversion and overconfidence on corporate strategies, the difficulties of predicting what will make us happy in the future, the challenges of properly framing risks at work and at home, the profound effect of cognitive biases on everything from playing the stock market to planning the next vacation—each of these can be understood only by knowing how the two systems work together to shape our judgments and decisions.
   Engaging the reader in a lively conversation about how we think, Kahneman reveals where we can and cannot trust our intuitions and how we can tap into the benefits of slow thinking. He offers practical and enlightening insights into how choices are made in both our business and our personal lives—and how we can use different techniques to guard against the mental glitches that often get us into trouble. Thinking, Fast and Slow will transform the way you think about thinking.',
   'Self Help',
   '9780374275631',
   '499',
   'October 25, 2011',
   '16.99',
   '4.17',
   'Thinking, Fast and Slow'),
('K.W. Jeter',
   'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1320437674i/9222475.jpg',
   'https://www.goodreads.com/book/show/9222475-infernal-devices?from_search=true&from_srp=true&qid=lpDh0Zykfc&rank=8',
   'HE INHERITED A WATCHMAKERS STORE - AND A WHOLE HEAP OF TROUBLE. But idle sometime-musician George has little talent for clockwork. And when a shadowy figure tries to steal an old device from the premises, George finds himself embroiled in a mystery of time travel, music and sexual intrigue. A genuine lost classic, a steampunk original whose time has come.',
   'Fantasy',
   '9780857660978',
   '384',
   'December 1, 1986',
   '16.99',
   '3.37',
   'Infernal Devices'),
('K.W. Jeter',
   'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1433161048i/1137215.jpg',
   'https://www.goodreads.com/book/show/1137215.Boneshaker?from_search=true&from_srp=true&qid=Y9zWN7Fial&rank=1',
   'In the early days of the Civil War, rumors of gold in the frozen Klondike brought hordes of newcomers to the Pacific Northwest. Anxious to compete, Russian prospectors commissioned inventor Leviticus Blue to create a great machine that could mine through Alaska’s ice. Thus was Dr. Blue’s Incredible Bone-Shaking Drill Engine born.
   But on its first test run the Boneshaker went terribly awry, destroying several blocks of downtown Seattle and unearthing a subterranean vein of blight gas that turned anyone who breathed it into the living dead.
   Now it is sixteen years later, and a wall has been built to enclose the devastated and toxic city. Just beyond it lives Blue’s widow, Briar Wilkes. Life is hard with a ruined reputation and a teenage boy to support, but she and Ezekiel are managing. Until Ezekiel undertakes a secret crusade to rewrite history.
   His quest will take him under the wall and into a city teeming with ravenous undead, air pirates, criminal overlords, and heavily armed refugees. And only Briar can bring him out alive.',
   'Fantasy',
   '9780765318411',
   '416',
   'June 1, 2009',
   '10.99',
   '3.52',
   'Boneshaker'),
('Danielle Valentine',
   'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1642779274i/59762456.jpg',
   'https://www.goodreads.com/book/show/59762456-how-to-survive-your-murder?from_search=true&from_srp=true&qid=0G2QTTJiAX&rank=1',
   'Alice Lawrence is the sole witness in her sister’s murder trial.
   And in the year since Claire’s death, Alice’s life has completely fallen apart. Her parents have gotten divorced, she’s moved into an apartment that smells like bologna, and she is being forced to face her sister’s killer and a courtroom full of people who doubt what she saw in the corn maze a year prior.
   Claire was an all-American girl, beautiful and bubbly, and a theater star. Alice was a nerd who dreamed of becoming a forensic pathologist and would rather stay at home to watch her favorite horror movies than party. Despite their differences, they were bonded by sisterhood and were each other’s best friends.
   Until Claire was taken away from her.
   On the first day of the murder trial, as Alice prepares to give her testimony, she is knocked out by a Sidney Prescott look-alike in the courthouse bathroom. When she wakes up, it is Halloween morning a year earlier, the same day Claire was murdered. Alice has until midnight to save her sister and find the real killer before he claims another victim.',
   'Horror',
   '9780593352014',
   '299',
   'August 30, 2022',
   '12.99',
   '3.78',
   'How to Survive Your Murder'),
('Kathryn Stockett',
   'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1622355533i/4667024.jpg',
   'https://www.goodreads.com/book/show/4667024-the-help',
   'Three ordinary women are about to take one extraordinary step.
   Twenty-two-year-old Skeeter has just returned home after graduating from Ole Miss. She may have a degree, but it is 1962, Mississippi, and her mother will not be happy till Skeeter has a ring on her finger. Skeeter would normally find solace with her beloved maid Constantine, the woman who raised her, but Constantine has disappeared and no one will tell Skeeter where she has gone.
   Aibileen is a black maid, a wise, regal woman raising her seventeenth white child. Something has shifted inside her after the loss of her own son, who died while his bosses looked the other way. She is devoted to the little girl she looks after, though she knows both their hearts may be broken.
   Minny, Aibileens best friend, is short, fat, and perhaps the sassiest woman in Mississippi. She can cook like nobodys business, but she can\'t mind her tongue, so she\'s lost yet another job. Minny finally finds a position working for someone too new to town to know her reputation. But her new boss has secrets of her own.
   Seemingly as different from one another as can be, these women will nonetheless come together for a clandestine project that will put them all at risk. And why? Because they are suffocating within the lines that define their town and their times. And sometimes lines are made to be crossed.
   In pitch-perfect voices, Kathryn Stockett creates three extraordinary women whose determination to start a movement of their own forever changes a town, and the way women, mothers, daughters, caregivers, friends, view one another. A deeply moving novel filled with poignancy, humor, and hope, The Help is a timeless and universal story about the lines we abide by, and the ones we don\'t.',
   'Fiction',
   '9780399155345',
   '464',
   'February 10, 2009',
   '15.99',
   '4.47',
   'The Help'),
('Stephen King',
 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1334416842i/830502.jpg',
 'https://www.goodreads.com/book/show/830502.It',
 'Welcome to Derry, Maine ...
It’s a small city, a place as hauntingly familiar as your own hometown. Only in Derry the haunting is real ...
They were seven teenagers when they first stumbled upon the horror. Now they are grown-up men and women who have gone out into the big world to gain success and happiness. But none of them can withstand the force that has drawn them back to Derry to face the nightmare without an end, and the evil without a name.',
 'Horror',
 '9780450411434',
 '1116',
 'January 1, 1986',
 '12.99',
 '4.25',
 'It'),
('GennaRose Nethercott',
 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1658241430i/60018639.jpg',
 'https://www.goodreads.com/book/show/60018639-thistlefoot',
 'The Yaga siblings--Bellatine, a young woodworker, and Isaac, a wayfaring street performer and con artist--have been estranged since childhood, separated both by resentment and by wide miles of American highway. But when they learn that they are to receive a mysterious inheritance, the siblings are reunited--only to discover that their bequest isn''t land or money, but something far stranger: a sentient house on chicken legs.
Thistlefoot, as the house is called, has arrived from the Yagas'' ancestral home in Russia--but not alone. A sinister figure known only as the Longshadow Man has tracked it to American shores, bearing with him violent secrets from the past: fiery memories that have hidden in Isaac and Bellatine''s blood for generations. As the Yaga siblings embark with Thistlefoot on a final cross-country tour of their family''s traveling theater show, the Longshadow Man follows in relentless pursuit, seeding destruction in his wake. Ultimately, time, magic, and legacy must collide--erupting in a powerful conflagration to determine who gets to remember the past and craft a new future.
An enchanted adventure illuminated by Jewish myth and adorned with lyrical prose as tantalizing and sweet as briar berries, Thistlefoot is an immersive modern fantasy saga by a bold new talent.',
 'Fantasy',
 '9780593468838',
 '448',
 'September 13, 2022',
 '14.99',
 '4.19',
 'Thistlefoot'),
('Silvia Moreno-Garcia',
 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1607462569i/53152636.jpg',
 'https://www.amazon.com/Mexican-Gothic/dp/1529402689',
 'After receiving a frantic letter from her newly-wed cousin begging for someone to save her from a mysterious doom, Noemí Taboada heads to High Place, a distant house in the Mexican countryside. She’s not sure what she will find—her cousin’s husband, a handsome Englishman, is a stranger, and Noemí knows little about the region.
Noemí is also an unlikely rescuer: She’s a glamorous debutante, and her chic gowns and perfect red lipstick are more suited for cocktail parties than amateur sleuthing. But she’s also tough and smart, with an indomitable will, and she is not afraid: Not of her cousin’s new husband, who is both menacing and alluring; not of his father, the ancient patriarch who seems to be fascinated by Noemí; and not even of the house itself, which begins to invade Noemí’s dreams with visions of blood and doom.
Her only ally in this inhospitable abode is the family’s youngest son. Shy and gentle, he seems to want to help Noemí, but might also be hiding dark knowledge of his family’s past. For there are many secrets behind the walls of High Place. The family’s once colossal wealth and faded mining empire kept them from prying eyes, but as Noemí digs deeper she unearths stories of violence and madness.
And Noemí, mesmerized by the terrifying yet seductive world of High Place, may soon find it impossible to ever leave this enigmatic house behind.',
 'Horror',
 '1529402689',
 '301',
 'June 30, 2020',
 '12.99',
 '3.68',
 'Mexican Gothic'),
('William Peter Blatty',
 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1375168676i/179780.jpg',
 'https://www.amazon.com/Exorcist-Anniversary-William-Peter-Blatty/dp/006209436X/ref=sr_1_1?crid=K413F6PIYL0Y&keywords=The+Exorcist+William+Peter+Blatty&qid=1665126488&qu=eyJxc2MiOiIyLjk4IiwicXNhIjoiMi4yMiIsInFzcCI6IjIuMTQifQ%3D%3D&s=books&sprefix=the+exorcist+william+peter+blatty%2Cstripbooks%2C109&sr=1-1',
 'Georgetown, Washington D.C. Actress and divorced mother Chris MacNeil starts to experience ''difficulties'' with her usually sweet-natured eleven-year-old daughter Regan. The child becomes afflicted by spasms, convulsions and unsettling amnesiac episodes; these abruptly worsen into violent fits of appalling foul-mouthed curses, accompanied by physical mutation. Medical science is baffled by Regan''s plight and, in her increasing despair, Chris turns to troubled priest and psychiatrist Damien Karras, who immediately recognises something profoundly malevolent in Regan''s distorted fetures and speech. On Karras''s recommendation, the Church summons Father Merrin, a specialist in the exorcism of demons . . .',
 'Horror',
 '006209436X',
 '400',
 'May 1, 1971',
 '14.99',
 '4.19',
 'The Exorcist'),
('Joe Hill',
 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1328043955i/153025.jpg',
 'https://www.amazon.com/Heart-Shaped-Box-Joe-Hill/dp/0061944890/ref=sr_1_1?crid=2JYBVDECX4MLM&keywords=Heart-Shaped+Box&qid=1665126747&qu=eyJxc2MiOiIzLjQxIiwicXNhIjoiMS41OCIsInFzcCI6IjIuMjQifQ%3D%3D&s=books&sprefix=heart-shaped+box%2Cstripbooks%2C112&sr=1-1',
 'An aging death-metal rock god, Judas Coyne, is a collector of the macabre: a cookbook for cannibals... a used hangman''s noose... a snuff film. But nothing he possesses is as unlikely or as dreadful as an item he learns is for sale on the Internet. For a thousand dollars, Jude will become the proud owner of a dead man''s suit, said to be haunted by the deceased''s restless spirit. Judas has spent a lifetime coping with ghosts - of an abusive father, of the lovers he callously abandoned, of the bandmates he betrayed - so what''s one more?
But what UPS delivers to his door in a black heart-shaped box is no imaginary or metaphorical ghost, it''s the real thing. And suddenly the suit''s previous owner is everywhere - behind the bedroom door... seated in Jude''s restored vintage Mustang... staring out from his widescreen TV - dangling a gleaming razor blade on a chain from one hand...',
 'Horror',
 '9780061147937',
 '376',
 'February 13, 2007',
 '12.69',
'3.85',
 'Heart-Shaped Box'),
('Washington Irving',
 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1348108368i/93261.jpg',
 'https://www.amazon.com/Legend-Sleepy-Hollow-Washington-Irving/dp/1530176514/ref=sr_1_1?crid=6T9YYFLJGLLF&keywords=The+Legend+of+Sleepy+Hollow&qid=1665126938&qu=eyJxc2MiOiI1LjI0IiwicXNhIjoiNS4xOSIsInFzcCI6IjQuMzgifQ%3D%3D&s=books&sprefix=the+legend+of+sleepy+hollow%2Cstripbooks%2C137&sr=1-1',
 'Ichabod Crane, a schoolteacher, came to Tarry Town in the glen of Sleepy Hollow to ply his trade in educating young minds. He was a gullible and excitable fellow, often so terrified by locals'' stories of ghosts that he would hurry through the woods on his way home, singing to keep from hysterics. Until late one night, he finds that maybe they''re not just stories. What is that dark, menacing figure riding behind him on a horse? And what does it have in its hands? And why wasn''t schoolteacher Crane ever seen in Sleepy Hollow again?',
 'Horror',
 '9780809594085',
 '108',
 'March 1, 2004',
 '3.68',
 '3.72',
 'The Legend of Sleepy Hollow'),
('Bret Easton Ellis',
 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1550545989i/44057908.jpg',
 'https://www.amazon.com/American-Psycho-Bret-Easton-Ellis/dp/0679735771/ref=sr_1_1?crid=33PMMDZ4W5ZL4&keywords=American+Psycho&qid=1665127156&qu=eyJxc2MiOiIyLjU5IiwicXNhIjoiMy4xMiIsInFzcCI6IjEuNTEifQ%3D%3D&s=books&sprefix=american+psycho%2Cstripbooks%2C137&sr=1-1',
 'Patrick Bateman is twenty-six and he works on Wall Street, he is handsome, sophisticated, charming and intelligent. He is also a psychopath. Taking us to head-on collision with America''s greatest dream—and its worst nightmare—American Psycho is bleak, bitter, black comedy about a world we all recognise but do not wish to confront.',
 'Horror',
 '9780679735779',
 '399',
 'March 6, 1991',
 '12.99',
 '3.81',
 'American Psycho'),
('Alex Garland',
 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1389059772i/8760.jpg',
 'https://www.amazon.com/28-Days-Later-Faber-Screenplays/dp/0571216536/ref=sr_1_1?crid=3M0487C2E0VV9&keywords=28+Days+Later+alex&qid=1665127315&s=books&sprefix=28+days+later+ale%2Cstripbooks%2C103&sr=1-1',
 'In this latest film from director Danny Boyle, a massive epidemic has swept the world, leaving in its wake a host of rabid humans seething with hatred and bent on destroying anyone untouched by the disease. Four seemingly unaffected people--a young man, a young woman, a father, and his daughter--flee London through an apocalyptic landscape as they try to reach the coast, beset along the way by attacks of "Infected" at every turn. When they arrive at an isolated house in the country, inhabited by a small group of soldiers, they think they have found a haven from the violence outside. But they soon find they''ve jumped from the frying pan into the fire.',
 'Horror',
 '9780571216536',
 '96',
 'April 17, 2003',
 '17.57',
 '4.11',
 '28 Days Later'),
('James Herbert',
 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1179544686i/929901.jpg',
 'https://www.amazon.com/48-James-Herbert/dp/0061052930/ref=sr_1_4?crid=4GZZII8JPA0T&keywords=james+herbert+books+48%5C&qid=1665127486&s=books&sprefix=james+herbert+books+48%2Cstripbooks%2C114&sr=1-4',
 'In 1945, Hitler unleashed the Blood Death on Britain as his final act of vengeance.
Those who died at once were the lucky ones. The really unfortunate took years. The survivors - people like me, who had the blood group that kept us safe from the disease - were now targets for those who believed our blood could save them.
I survived for three years. I lived alone, spending my days avoiding the fascist Blackshirts who wanted my blood for their dying leader. Then I met the others - and life got complicated all over again . . .',
 'Horror',
 '9782258049048',
 '336',
 'November 4, 1996',
 '16.99',
 '3.77',
 '48'),
('Benjamin Percy',
 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1499860280i/30971743.jpg',
 'https://www.amazon.com/Dark-Net-Benjamin-Percy/dp/1328915379/ref=sr_1_2?crid=136TZJQ4RANC6&keywords=The+Dark+Net&qid=1665127686&qu=eyJxc2MiOiIyLjc1IiwicXNhIjoiMS44NyIsInFzcCI6IjIuMDQifQ%3D%3D&s=books&sprefix=the+dark+net%2Cstripbooks%2C125&sr=1-2',
 'The Dark Net is real. An anonymous and often criminal arena that exists in the secret far reaches of the Web, some use it to manage Bitcoins, pirate movies and music, or traffic in drugs and stolen goods. And now an ancient darkness is gathering there as well. This force is threatening to spread virally into the real world unless it can be stopped by members of a ragtag crew:
Twelve-year-old Hannah - who has been fitted with the Mirage, a high-tech visual prosthetic to combat her blindness - wonders why she sees shadows surrounding some people.
Lela, a technophobic journalist, has stumbled upon a story nobody wants her to uncover.
Mike Juniper, a one-time child evangelist who suffers from personal and literal demons, has an arsenal of weapons stored in the basement of the homeless shelter he runs.
And Derek, a hacker with a cause, believes himself a soldier of the Internet, part of a cyber army akin to Anonymous.
They have no idea what the Dark Net really contains.
Set in present-day Portland, The Dark Net is a cracked-mirror version of the digital nightmare we already live in, a timely and wildly imaginative techno-thriller about the evil that lurks in real and virtual spaces, and the power of a united few to fight back.',
 'Horror',
 '9780544750333',
 '256',
 'August 1, 2017',
 '9.59',
 '3.22',
 'The Dark Net'),
('Garfield Reeves-Stevens',
 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1385343990i/1293224.jpg',
 'https://www.amazon.com/Dreamland-Garfield-Reeves-Stevens/dp/0446361550/ref=sr_1_1?crid=3NU8JE0P6LIS9&keywords=Dreamland+Garfield+Reeves-Stevens&qid=1665128116&s=books&sprefix=dreamland+garfield+reeves-stevens%2Cstripbooks%2C119&sr=1-1',
 'In "Dreamland," an ultimate theme park run by lifelike robots, sixty thousand unsuspecting guests who have been promised the time of their lives, are unaware that an evil that preys on childhood fears is about to strike',
 'Horror',
 '9780446361552',
 '422',
 'January 1, 1985',
 '18.98',
 '3.19',
 'Dreamland' );






INSERT INTO reviews(published_date, rating, review_body, title, book_id, user_id) VALUES
('2022-03-30 01:53:19', '3', 'This book was aight', 'aight', '1', '1'),
('2022-06-30 06:53:19', '5', 'This book gave me the chills. Definitely worth reading even as an adult! Everyone should read this. Even you, Nicholas...', 'Greatest Book','2', '2'),
('2022-09-30 08:53:19', '1', 'This is too scary of a book.. Do not recommend. I tried reading it as a bedtime story.. Big Regrets!', 'Too scary, not good', '3', '3'),
('2022-01-29 09:53:19', '4', 'My experience with reading this book was astounding. I am only rating it a four though because of the author.', 'Great read!', '4', '4'),
('2022-10-31 10:53:19', '2', 'I had high hopes this book since the author has been so revered. It was hard to follow and i had too much of a hard time getting through each chapter. Rating is 2 stars just to be nice.', 'Not Good Enough.', '5', '5'),
('2022-08-30 12:53:19', '3', 'I was left with so many questions, in the end I just hope that this becomes a series otherwise its not worth the read.', 'Could be better', '6', '6'),
('2022-04-30 11:53:19', '5', 'I am raving over this book. I have searched for the perfect read over the summer and this has uplifted my spirits!', 'The best book in the world!', '7', '7'),
('2022-01-30 03:53:19', '1', 'If you are reading this i beg you not to read this book. Save yourself from the perils within..', 'If only I could give 0 stars', '8', '8'),
('2022-12-25 06:53:19', '5', 'Wow!! I love it when I read a book and it leaves me with a feel good feeling. This book will leave you at the edge of your seat but is tied up well in the ending. I recommend.', 'The Bomb.Com', '9', '9'),
('2022-07-20 02:53:19','5', 'What isnt there to love?? I cannot wait to see what other books this author comes out with. I greatly enjoyed reading this book!', 'A Must Read', '10', '10');

INSERT INTO liked_books (book_id, user_id) VALUES
('1', '2'),
('2','3'),
('3', '6'),
('4', '7'),
('5', '1'),
('6', '4'),
('7', '8'),
('8', '10'),
('9', '5'),
('10', '9'),
('10', '5'),
('2','6'),
('3', '8'),
('4', '10'),
('5', '2'),
('6', '1'),
('7', '4'),
('8', '7'),
('9', '9'),
('1', '3');


